DROP DATABASE IF EXISTS BIBLIOTECAEXAMEN;
CREATE DATABASE BIBLIOTECAEXAMEN;
USE BIBLIOTECAEXAMEN;

CREATE TABLE IDIOMAS(
IdIdioma INTEGER PRIMARY KEY,
Idioma VARCHAR(20))ENGINE = InnoDB;

CREATE TABLE NACIONALIDADES(
IdNacionalidad INTEGER PRIMARY KEY,
Nacionalidad VARCHAR(20))ENGINE = InnoDB;

CREATE TABLE AUTORES(
IdAutor INTEGER PRIMARY KEY,
Nombre VARCHAR(30),
IdNacionalidad INTEGER,
FOREIGN KEY (IdNacionalidad) REFERENCES Nacionalidades (IdNacionalidad))ENGINE = InnoDB;

CREATE TABLE Temas(
IdTema INTEGER PRIMARY KEY,
Tema VARCHAR(30))ENGINE = InnoDB;

CREATE TABLE EDITORIALES(
IdEditorial INTEGER PRIMARY KEY,
Nombre VARCHAR(50),
Direccion VARCHAR(50),
Telefono CHAR(9))ENGINE = InnoDB;

CREATE TABLE Libros(
IdLibro INTEGER PRIMARY KEY,
Titulo VARCHAR(50),
IdIdioma INTEGER,
IdEditorial INTEGER,
IdAutor INTEGER,
IdTema INTEGER,
AnhoPublicacion SMALLINT,
DiasMaxPrestamo SMALLINT,
FOREIGN KEY (IdIdioma) REFERENCES Idiomas (IdIdioma),
FOREIGN KEY (IdEditorial) REFERENCES Editoriales (IdEditorial),
FOREIGN KEY (IdAutor) REFERENCES Autores (IdAutor),
FOREIGN KEY (IdTema) REFERENCES Temas (IdTema))ENGINE = InnoDB;

CREATE TABLE EJEMPLARES(
IdLibro INTEGER,
IdEjemplar INTEGER,
Ubicacion VARCHAR(20),
Edicion VARCHAR(15),
Precio DOUBLE,
Disponible BOOL DEFAULT TRUE,
PRIMARY KEY (IdLibro, IdEjemplar),
FOREIGN KEY (IdLibro) REFERENCES Libros (IdLibro))ENGINE = InnoDB;

CREATE TABLE SOCIOS(
IdSocio INTEGER PRIMARY KEY,
Nombre VARCHAR(20),
Apellidos VARCHAR(30),
Direccion VARCHAR(50),
Telefono CHAR(9))ENGINE = InnoDB;

CREATE TABLE SANCIONES(
IdSancion INTEGER PRIMARY KEY,
IdSocio INTEGER,
FechaSancion DATE,
FOREIGN KEY (IdSocio) REFERENCES Socios (IdSocio))ENGINE = InnoDB;

CREATE TABLE PRESTAMOS(
IdPrestamo INTEGER PRIMARY KEY,
IdLibro INTEGER,
IdEjemplar INTEGER,
IdSocio INTEGER,
FechaPrestamo DATE,
FechaDevolucion DATE,
Devuelto BOOL,
FOREIGN KEY (IdLibro, IdEjemplar) REFERENCES Ejemplares (IdLibro, IdEjemplar),
FOREIGN KEY (IdSocio) REFERENCES Socios (IdSocio))ENGINE = InnoDB;